#!/bin/sh
#
# Default boot initalization
#
echo "calling default script"
case "$1" in
  start)
 	echo "Mounting Filesystems..."
	/bin/mount -a
	echo "Setting hostname"
	/bin/hostname -F /etc/hostname
	/bin/mkdir -pv /{etc,tmp,proc,sys,dev,home,mnt,root,usr/{bin,sbin,lib},var}
	/bin/mkdir -pv /etc/network/if-{post-{up,down},pre-{up,down},up,down}.d
	;;
  stop)
	echo -n "Unmounting Filesystem..."
	/bin/umount -a
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

